Num1 = int(input("Num1 :"))
Num2 = int(input("Num2 :"))
print("Calculate +,-,*,/")
print(Num1,"+",Num2,"=",Num1+Num2)
print(Num1,"-",Num2,"=",Num1-Num2)
print(Num1,"*",Num2,"=",Num1*Num2)
print(Num1,"/",Num2,"=",int(Num1/Num2))